DROP DATABASE IF EXISTS SECURISE_DB;

CREATE DATABASE SECURISE_DB CHARACTER SET utf8;
USE SECURISE_DB;

CREATE TABLE UTILISATEURS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    mdp VARCHAR(255) NOT NULL,
    dateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);